version: '3'

services:
  spooderfy_website:
    build: .
    container_name: spooderfy_website
    image: spooderfy_website
    restart: always
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "5050:8080"

networks:
  default:
    external:
      name: spooderfy_network